language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache/files

before_script:
    - composer install

script: vendor/bin/phpunit

matrix:
    include:
        - php: 7.1
        - php: 7.3
