language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - composer install

script: phpunit

matrix:
    include:
        - php: 7.2
